#%RAML 1.0 NamedExample
confirmBooking:
  StatusCode : 204,
  Description : Ticket is confirmed, Please find the booking details.,
  B_ID : B12345432,
  T_ID : T12345432,
  M_ID : M12345432,
  Date : 2021-12-12,
  Slot : 11:00,
  NoOfSeats : 10