#%RAML 1.0 NamedExample
theatre:
  -
    ID: 200,
    NAME: Ganga,
    ADDRESS: Mahathma Gandhi road,Bangalore,
    CONTACT: 44123456,
  -
    ID: 201,
    NAME: Gauri,
    ADDRESS: Shivaji Park Road, Bangalore,
    CONTACT: 44123457,

